const hackerUserAgents = [
  "008",
  "ABACHOBot",
  "Accoona-AI-Agent",
  "AddSugarSpiderBot",
  "AnyApexBot",
  "Arachmo",
  "sqlmap",
  "acunetix",
  "nmap",
  "masscan",
  "keylogger",
  "botnet",
  "crawler",
  "scraper",
  "rat",
  "vpn",
  "malware",
  "ransomware",
  "exploit",
  "xss",
  "lfi",
  "rfi",
  "cmd.exe",
  "powershell",
  "bash -i",
  "revshell",
  "blackwidow",
  "blackhat",
  "badbot",
  "evilbot",
  "penetration tool",
  "fuzzer",
  "hydra",
  "wpscan",
  "dirbuster",
  "joomlascan",
  "wordpressscan",
  "shodan",
  "arachni",
  "vega",
  "metasploit",
  "bruteforce",
  "phishing",
  "python-requests",
  "libwww-perl",
  "curl",
  "wget",
  "massscanner",
  "0day",
  "webscanner",
  "zgrab",
  "zeus-scanner",
  "webshag",
  "spiderfoot",
  "dnsenum",
  "bbscan",
  "whatweb",
  "appspider",
  "burpsuite",
  "zaproxy",
  "netsparker",
  "openvas",
  "nessus",
  "sitehound",
  "smuggle",
  "inql",
  "sentry",
  "sublist3r",
  "webRTC",
  "webRTC leak",
  "webRTC leak test",
  "webRTC leak test tool",
  "webRTC leak test tool online",
  "webRTC leak test tool online free",
  "webRTC leak test tool online free without registration",
  "webRTC leak test tool online free without registration and download",
  "webRTC leak test tool online free without registration and download and installation",
  "webRTC leak test tool online free without registration and download and installation and signup",
  "webRTC leak test tool online free without registration and download and installation and signup and login",
  "vpn",
  "vpn free",
  "vpn free trial",
  "vpn free trial 30 days",
  "vpn free trial 30 days no credit card",
  "vpn free trial 30 days no credit card required",
  "vpn free trial 30 days no credit card required 2021",
  "vpn free trial 30 days no credit card required 2022",
  "vpn free trial 30 days no credit card required 2023",
  "vpn free trial 30 days no credit card required 2024",
  "energie bot",
  "energie spider",
  "energie crawler",
  "energie scanner",
  "MJ12bot",
  "AhrefsBot",
  "SemrushBot",
  "DotBot",
  "Baiduspider",
  "YandexBot",
  "Sogou",
  "Exabot",
  "facebot",
  "ia_archiver",
  "PetalBot",
  "Seekport",
  "BLEXBot",
  "Cliqzbot",
  "DuckDuckBot",
  "Googlebot",
  "bingbot",
  "Slurp",
  "Teoma",
  "Gigabot",
  "Scrapy",
  "Screaming Frog SEO Spider",
  "GrapeshotCrawler",
  "LinkpadBot",
  "MegaIndex",
  "SeznamBot",
  "SputnikBot",
  "UptimeRobot",
  "Wget",
  "curl",
  "python-requests",
  "libwww-perl",
  "masscan",
  "sqlmap",
  "acunetix",
  "nmap",
  "dirbuster",
  "wpscan",
  "nikto",
  "fuzz",
  "athena",
  "peerconnection",
  "hydra",
  "webrtc",
  "metasploit",
  "bruteforce",
  "phishing",
  "penetration tool",
  "exploit",
  "xss",
  "lfi",
  "rfi",
  "cmd.exe",
  "powershell",
  "bash -i",
  "revshell",
  "blackwidow",
  "blackhat",
  "badbot",
  "evilbot",
  "botnet",
  "crawler",
  "scraper",
  "rat",
  "malware",
  "ransomware",
  "0day",
  "webscanner",
  "zgrab",
  "zeus-scanner",
  "webshag",
  "spiderfoot",
  "dnsenum",
  "bbscan",
  "whatweb",
  "appspider",
  "burpsuite",
  "zaproxy",
  "netsparker",
  "openvas",
  "nessus",
  "sitehound",
  "smuggle",
  "inql",
  "sentry",
  "sublist3r",
  "screen-capture",
  "screen-recorder",
  "screen recording",
  "screen recorder",
  "screen-stream",
  "screen-streaming-bot",
  "stream-recorder",
  "desktop-capture",
  "desktop-recorder",
  "capturebot",
  "mirroringbot",
  "remote-desktop-bot",
  "screen-cast",
  "screenleech",
  "recordbot",
  "screencap-bot",
  "virtualcam",
  "spyrecorder",
  "snifferspy",
  "dom.push.connection.enabled",
  "ice.proxy_only",
  "proxy_only_if_behind_proxy",
  "Monitor.WebRTC.connectiom",
  "media.peerconnection.ice.obfuscate_host_addresses",
  "media.peerconnection.enabled",
  "openvpn", "nordvpn", "protonvpn", "expressvpn", "windscribe", "cyberghost", "surfshark", "pia", "privadovpn"
];

const userAgent = navigator.userAgent.toLowerCase();
const isBlocked = document.cookie.split('; ').find(row => row.startsWith('blocked='));

if (isBlocked) {
  alert('🚫 Access Denied - You have been blocked.');
  window.location.href = "https://www.google.com";
} else if (hackerUserAgents.some(agent => userAgent.includes(agent))) {
  document.cookie = "blocked=true; path=/; max-age=31536000"; // Block for 1 year
  alert('🚫 Access Denied - Malicious user agent detected.');
 sleep(2000);
  window.location.href = "https://www.google.com";
}
